### ISSUE TITLE
compile error without MKL in ubuntu

### ISSUE THREAD

**Issue by f1r1o1n1t1** [michalpolic/usfm.github.io#1]
I am compiling the project in ubuntu 18.04. With Matlab but without MKL. 
In the process of 'make',  the first error is :
.../usfm.github.io/src/USfM/usfm_Algorithm.cpp:15:10: fatal error: mkl.h: No such file or directory
 #include "mkl.h"
Then I comment this line: //#include "mkl.h"
Several other errors still happen:
(1)/home/groot/projects/usfm.github.io/src/./USfM/usfm_data_Image.hpp:56:13: error: extra qualification ‘usfm::Image::’ on member ‘numParams’ [-fpermissive]
   const int Image::numParams() const;
(2)/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:378:9: error: ‘isnan’ was not declared in this scope
     if (isnan(it.value()))
(3)/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:396:3: error: ‘MKL_INT’ was not declared in this scope
   MKL_INT N = A.rows();
   ^~~~~~~
/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:397:12: error: ‘ipiv’ was not declared in this scope
   MKL_INT *ipiv = (MKL_INT*) malloc(N * sizeof(MKL_INT));
            ^~~~
/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:397:12: note: suggested alternative: ‘init’
   MKL_INT *ipiv = (MKL_INT*) malloc(N * sizeof(MKL_INT));
            ^~~~
            init
/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:397:28: error: expected primary-expression before ‘)’ token
   MKL_INT *ipiv = (MKL_INT*) malloc(N * sizeof(MKL_INT));
                            ^
/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:398:22: error: ‘LAPACK_COL_MAJOR’ was not declared in this scope
   if (LAPACKE_dgetrf(LAPACK_COL_MAJOR, N, N, A.data(), N, ipiv) != 0)
                      ^~~~~~~~~~~~~~~~
/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:398:40: error: ‘N’ was not declared in this scope
   if (LAPACKE_dgetrf(LAPACK_COL_MAJOR, N, N, A.data(), N, ipiv) != 0)
                                        ^
/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:398:7: error: ‘LAPACKE_dgetrf’ was not declared in this scope
   if (LAPACKE_dgetrf(LAPACK_COL_MAJOR, N, N, A.data(), N, ipiv) != 0)
       ^~~~~~~~~~~~~~
/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:401:22: error: ‘LAPACK_COL_MAJOR’ was not declared in this scope
   if (LAPACKE_dgetri(LAPACK_COL_MAJOR, N, A.data(), N, ipiv) != 0)
                      ^~~~~~~~~~~~~~~~
/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:401:40: error: ‘N’ was not declared in this scope
   if (LAPACKE_dgetri(LAPACK_COL_MAJOR, N, A.data(), N, ipiv) != 0)
                                        ^
/home/groot/projects/usfm.github.io/src/USfM/usfm_Algorithm.cpp:401:7: error: ‘LAPACKE_dgetri’ was not declared in this scope
   if (LAPACKE_dgetri(LAPACK_COL_MAJOR, N, A.data(), N, ipiv) != 0)

For the first error, I replace 'usfm::Image::' with 'Image::'.
For the second error, I add '#include <math.h>' in usfm_Algorithm.hpp
But for the third error, I wonder whether MKL is necessary for this  project. I am looking forward for you reply! Thank you!

**Comment by mpol007** [comment]
Thank you for posting the issue. The code needs Blas and Lapack library which are inside MKL library. There are approx. 5 lines which use the library (doing the inversion in NBUP and SVD in older methods) but in case of using Eigen is code too slow. I should add a test for proper linking. I will look at the code later this day and send more detailed info or update.

**Comment by michalpolic** [comment]
I am sorry for the late answer. Try the last commit, and it should work with Eigen (Eigen can be compiled with BLAS and LAPAC to improve speed).

The problem was in the inversion of the symmetric matrix, which is preferred to be computed using MKL or some optimized BLAS/LAPACK library. There is also code for CBLAS (if MKL is not available) in commented part of inversion function. I didn't make it running because of some linking errors. Any help is welcomed.
