### ISSUE TITLE
bad memory alloc in computeUncertaintyOfPoints function

### ISSUE THREAD

**Issue by yinghuasha** [michalpolic/usfm.github.io#2]
In the function of computeUncertaintyOfPoints，a sparse  matrix is forced converted to common matrix，which leads insufficient memory. Eigen::MatrixXf fiAs = iAs.cast<float>(); how to fix this problem?

**Comment by michalpolic** [comment]
The conversion was changend. It should be working now.

**Comment by yinghuasha** [comment]
I have solved this problem already，thank you！

**Comment by yinghuasha** [comment]
#pragma omp parallel for
		for (int i = 0; i < num_pts; ++i) {				// each point m has values on three rows h
			std::vector<float> &r0 = h[3 * i + 0];
			std::vector<float> &r1 = h[3 * i + 1];
			std::vector<float> &r2 = h[3 * i + 2];
			int row_from = rowsY[3 * i];
			int row_to = rowsY[3 * i + 1];
			int ncols = row_to - row_from;
		
			int startCol = i * 9 / iARows;
			int startRow = i * 9 - startCol * iARows;

			Eigen::Matrix<float, 9, 1, Eigen::ColMajor> blockIA = iAs.block(startRow, startCol, 9, 1).cast<float>();

			float* iA = blockIA.data();

**Comment by michalpolic** [comment]
The block function on sparse matrices is slow because of searching all the array each time you call it. The order of parameters in sparse matrix correspond with used indexing in followed code. So, the simples and fasters way should be copy the values of sparse matrix into the float array. See the last commit.

**Comment by yinghuasha** [comment]
But the flowing index of the array is changed compared with previous version, as it only stores non-zero values. In previous version, all values are stored in the matrix (Eigen::MatrixXf fiAs = iAs.cast<float>();). So is there a problem?
v00 + iA[9 * i + 0], v01 + iA[9 * i + 3], v02 + iA[9 * i + 6],
v01 + iA[9 * i + 1], v11 + iA[9 * i + 4], v12 + iA[9 * i + 7],
v02 + iA[9 * i + 2], v12 + iA[9 * i + 5], v22 + iA[9 * i + 8];

**Comment by michalpolic** [comment]
You are right. The formula should add the iA diagonal blocks. Each block has 9 values. There was mistake in the original code. Thank you for noting that.
